services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data    

  adminer:
    image: adminer
    ports:
      - 8080:8080
